server.port: 8082

spring:
  application:
    name: billing
  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  flyway:
    enable: true
    locations: classpath:db/migration,classpath:db/testdata
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://localhost:5432/billing